[package]
name = "psbt"
version = { workspace = true }
description = "Modern, minimalistic & standard-compliant PSBT library"
keywords = { workspace = true }
categories = { workspace = true }
readme = "../README.md"
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
amplify = { workspace = true }
bp-std = { workspace = true }
bp-dbc = { workspace = true }
bp-seals = { workspace = true }
commit_verify = { workspace = true }
descriptors = { workspace = true }
strict_encoding = { workspace = true }
indexmap = { workspace = true }
base64 = "0.21.5"
chrono = "0.4.31"
serde_crate = { workspace = true, optional = true }

[features]
default = []
all = ["serde"]
serde = ["serde_crate", "bp-std/serde", "indexmap/serde"]
